- name: Setup testuser with SSH key
  hosts: all
  become: yes
  tasks:
  
    - name: Create testuser with sudo privileges
      user:
        name: testuser
        shell: /bin/bash
        state: present
        create_home: yes
        groups: sudo
        append: yes

    - name: Allow testuser to use sudo without password
      copy:
        dest: /etc/sudoers.d/80-ansible-sudo-user
        content: "testuser ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'

    - name: Create .ssh directory
      file:
        path: /home/testuser/.ssh
        state: directory
        owner: testuser
        group: testuser
        mode: '0700'

    - name: Install public key into authorized_keys
      copy:
        src: /home/student/.ssh/testuser.pub 
        dest: /home/testuser/.ssh/authorized_keys
        owner: testuser
        group: testuser
        mode: '0600'

    - name: Copy private key to VM
      copy:
        src: /home/student/.ssh/testuser  
        dest: /home/testuser/.ssh/testuser
        owner: testuser
        group: testuser
        mode: '0600'
