name: CICD test branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  Validate:
    name: Terraform validate
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform fmt
        run: terraform fmt -check

  Terraform:
    name: Terraform provision
    runs-on: self-hosted
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform apply 
        run: |
          terraform apply --auto-approve
        continue-on-error: true


      - name: List files before upload
        run: ls -la    

      - name: Upload Terraform state
        uses: actions/upload-artifact@v4
        with:
          name: terraform.tfstate
          path: terraform.tfstate


      - name: cat inventory.ini
        run: | 
          cat inventory.ini

