name: CICD omgeving opzetten en docker container 'hello world' installeren 

#code checken
#omgeving opbouwen met Terraform
#playbooks draaien met Ansible

on:
  push:
    branches: [main,test] 
    paths:
      - '*.tf'
  pull_request:
    branches: [main,test]
    paths:
      - '*.tf'

jobs:
  terraform-validate:
    name: Terraform validate
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform fmt
        run: terraform fmt -check

  ansible-validate:
    name: Ansible validate
    runs-on: self-hosted
    steps:
      - name: Install Ansible and ansible-lint
        run: |
          pip install --break-system-packages ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint playbooks/testuser_playbook.yml
        continue-on-error: true 

      - name: Run ansible-lint
        run: |
          ansible-lint playbooks/docker-role_playbook.yml
        continue-on-error: true 

  provision:
    name:  Omgeving opzetten
    runs-on: self-hosted
    needs: terraform-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply --auto-approve

      - name: echo pwd
        run: echo "$PWD"

      - name: check inventory.ini
        run: cat inventory.ini

      - name: check inventory
        run: ansible-inventory -i inventory.ini --list

      - name: Run testuser playbook
        run: ansible-playbook -i inventory.ini playbooks/testuser_playbook.yml
        
      - name: Install Docker role from Galaxy
        run: ansible-galaxy install BurenRaas.docker

      - name: Run testuser playbook
        run: ansible-playbook -i inventory.ini playbooks/docker-role_playbook.yml

        



