name: CICD 

#Code checken
#omgeving opbouwen met Terraform
#playbooks draaien met Ansible

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform-validate:
    name: Terraform validate
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform fmt
        run: terraform fmt -check

  ansible-validate:
    name: Ansible validate
    runs-on: self-hosted
    steps:
      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint playbooks/testuser_playbook.yml

  terraform-apply:
    name: Terraform provision
    runs-on: self-hosted
    needs: terraform-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply --auto-approve

  ansible-deploy:
    name: Ansible tasks
    runs-on: self-hosted
    needs: terraform-apply, ansible-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show inventory
        run: cat inventory.ini

      - name: Run testuser playbook
        run: ansible-playbook -i inventory.ini playbooks/testuser_playbook.yml

      - name: Install Docker role from Galaxy
        run: ansible-galaxy install BurenRaas.docker

      - name: Run Docker role playbook
        run: ansible-playbook -i inventory.ini ansible-role-docker/playbook.yml
