name: CICD 

#code checken
#omgeving opbouwen met Terraform
#playbooks draaien met Ansible

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]

jobs:
  terraform-validate:
    name: Terraform validate
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform fmt
        run: terraform fmt -check

  ansible-validate:
    name: Ansible validate
    runs-on: self-hosted
    steps:
      - name: Install Ansible and ansible-lint
        run: |
          pip install --break-system-packages ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint playbooks/testuser_playbook.yml
        continue-on-error: true 

  terraform-apply:
    name: Terraform provision
    runs-on: self-hosted
    needs: terraform-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply --auto-approve

      - name: check inventory.ini
        run: cat inventory.ini

      - name: check inventor
        run: ansible-inventory -i /home/student/IAC/les06/inventory.ini --list

      - name: echo pwd
        run: echo "$PWD"

      - name: Run testuser playbook
        run: ansible-playbook -i ~/IAC/les06/inventory.ini playbooks/testuser_playbook.yml

      - name: Install Docker role from Galaxy
        run: ansible-galaxy install BurenRaas.docker

      - name: Run Docker role playbook
        run: ansible-playbook -i ~/IAC/les06/inventory.ini ansible-role-docker/playbook.yml


  ansible-deploy:
    name: Ansible tasks
    runs-on: self-hosted
    needs:  terraform-apply
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: check inventory.ini
        run: cat inventory.ini

      - name: Run testuser playbook
        run: ansible-playbook -i ~/IAC/les06/inventory.ini playbooks/testuser_playbook.yml

      - name: Install Docker role from Galaxy
        run: ansible-galaxy install BurenRaas.docker

      - name: Run Docker role playbook
        run: ansible-playbook -i ~/IAC/les06/inventory.ini ansible-role-docker/playbook.yml
